CREATE TABLE Category(
Id INT PRIMARY KEY IDENTITY NOT NULL ,
[Name] NVARCHAR(255) NOT NULL
)
CREATE TABLE Product(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] NVARCHAR(255) NOT NULL,
Quantity INT NOT NULL,
Price DECIMAL NOT NULL,
CategoryId INT NOT NULL FOREIGN KEY REFERENCES Category(Id)
)

